// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.example.soap.stubs;

public interface ChambreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chambre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string numero = 2;</code>
   * @return The numero.
   */
  java.lang.String getNumero();
  /**
   * <code>string numero = 2;</code>
   * @return The bytes for numero.
   */
  com.google.protobuf.ByteString
      getNumeroBytes();

  /**
   * <code>bool disponible = 3;</code>
   * @return The disponible.
   */
  boolean getDisponible();

  /**
   * <code>double prix = 4;</code>
   * @return The prix.
   */
  double getPrix();

  /**
   * <code>.TypeChambre type = 5;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeChambre type = 5;</code>
   * @return The type.
   */
  com.example.soap.stubs.TypeChambre getType();
}
