// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.example.soap.stubs;

public interface DeleteReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indique si la suppression a réussi
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
