// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.example.soap.stubs;

public interface GetAllReservationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllReservationsRequest)
    com.google.protobuf.MessageOrBuilder {
}
