// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.example.soap.stubs;

public final class Hotel {
  private Hotel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hotel.proto\"\210\001\n\013Reservation\022\n\n\002id\030\001 \001(" +
      "\003\022\027\n\006client\030\002 \001(\0132\007.Client\022\031\n\007chambre\030\003 " +
      "\001(\0132\010.Chambre\022\022\n\ndate_debut\030\004 \001(\t\022\020\n\010dat" +
      "e_fin\030\005 \001(\t\022\023\n\013preferences\030\006 \001(\t\"S\n\006Clie" +
      "nt\022\n\n\002id\030\001 \001(\003\022\013\n\003nom\030\002 \001(\t\022\016\n\006prenom\030\003 " +
      "\001(\t\022\r\n\005email\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"c\n" +
      "\007Chambre\022\n\n\002id\030\001 \001(\003\022\016\n\006numero\030\002 \001(\t\022\022\n\n" +
      "disponible\030\003 \001(\010\022\014\n\004prix\030\004 \001(\001\022\032\n\004type\030\005" +
      " \001(\0162\014.TypeChambre\"|\n\030CreateReservationR" +
      "equest\022\021\n\tclient_id\030\001 \001(\003\022\022\n\nchambre_id\030" +
      "\002 \001(\003\022\022\n\ndate_debut\030\003 \001(\t\022\020\n\010date_fin\030\004 " +
      "\001(\t\022\023\n\013preferences\030\005 \001(\t\"#\n\025GetReservati" +
      "onRequest\022\n\n\002id\030\001 \001(\003\"\210\001\n\030UpdateReservat" +
      "ionRequest\022\n\n\002id\030\001 \001(\003\022\021\n\tclient_id\030\002 \001(" +
      "\003\022\022\n\nchambre_id\030\003 \001(\003\022\022\n\ndate_debut\030\004 \001(" +
      "\t\022\020\n\010date_fin\030\005 \001(\t\022\023\n\013preferences\030\006 \001(\t" +
      "\"&\n\030DeleteReservationRequest\022\n\n\002id\030\001 \001(\003" +
      "\",\n\031DeleteReservationResponse\022\017\n\007success" +
      "\030\001 \001(\010\"8\n\023ReservationResponse\022!\n\013reserva" +
      "tion\030\001 \001(\0132\014.Reservation\"5\n\017ReservationL" +
      "ist\022\"\n\014reservations\030\001 \003(\0132\014.Reservation\"" +
      "\033\n\031GetAllReservationsRequest*2\n\013TypeCham" +
      "bre\022\n\n\006PETITE\020\000\022\013\n\007MOYENNE\020\001\022\n\n\006GRANDE\020\002" +
      "2\360\002\n\022ReservationService\022D\n\021CreateReserva" +
      "tion\022\031.CreateReservationRequest\032\024.Reserv" +
      "ationResponse\022>\n\016GetReservation\022\026.GetRes" +
      "ervationRequest\032\024.ReservationResponse\022B\n" +
      "\022GetAllReservations\022\032.GetAllReservations" +
      "Request\032\020.ReservationList\022D\n\021UpdateReser" +
      "vation\022\031.UpdateReservationRequest\032\024.Rese" +
      "rvationResponse\022J\n\021DeleteReservation\022\031.D" +
      "eleteReservationRequest\032\032.DeleteReservat" +
      "ionResponseB\032\n\026com.example.soap.stubsP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "Client", "Chambre", "DateDebut", "DateFin", "Preferences", });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "Numero", "Disponible", "Prix", "Type", });
    internal_static_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationRequest_descriptor,
        new java.lang.String[] { "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_ReservationList_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ReservationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationList_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
