// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.example.soap.stubs;

public interface ReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.example.soap.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  com.example.soap.stubs.ReservationOrBuilder getReservationOrBuilder();
}
