// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.example.soap.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 2;</code>
   * @return The client.
   */
  com.example.soap.stubs.Client getClient();
  /**
   * <code>.Client client = 2;</code>
   */
  com.example.soap.stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.Chambre chambre = 3;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 3;</code>
   * @return The chambre.
   */
  com.example.soap.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 3;</code>
   */
  com.example.soap.stubs.ChambreOrBuilder getChambreOrBuilder();

  /**
   * <code>string date_debut = 4;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string date_debut = 4;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string date_fin = 5;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string date_fin = 5;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 6;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 6;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
